// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'store_in_radius.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StoreInRadius _$StoreInRadiusFromJson(Map<String, dynamic> json) =>
    StoreInRadius(
      json['bizesId'] as String?,
      json['bizesNm'] as String?,
      json['brchNm'] as String?,
      json['indsLclsCd'] as String?,
      json['indsLclsNm'] as String?,
      json['indsMclsCd'] as String?,
      json['indsMclsNm'] as String?,
      json['indsSclsCd'] as String?,
      json['indsSclsNm'] as String?,
      json['ksicCd'] as String?,
      json['ksicNm'] as String?,
      json['ctprvnCd'] as String?,
      json['ctprvnNm'] as String?,
      json['signguCd'] as String?,
      json['signguNm'] as String?,
      json['adongCd'] as String?,
      json['adongNm'] as String?,
      json['ldongCd'] as String?,
      json['ldongNm'] as String?,
      json['lnoCd'] as String?,
      json['plotSctCd'] as String?,
      json['plotSctNm'] as String?,
      json['lnoMnno'],
      json['lnoSlno'],
      json['lnoAdr'] as String?,
      json['rdnmCd'] as String?,
      json['rdnm'] as String?,
      json['bldMnno'],
      json['bldSlno'],
      json['bldMngNo'] as String?,
      json['bldNm'] as String?,
      json['rdnmAdr'] as String?,
      json['oldZipcd'] as String?,
      json['newZipcd'] as String?,
      json['dongNo'] as String?,
      json['flrNo'] as String?,
      json['hoNo'] as String?,
      (json['lon'] as num?)?.toDouble(),
      (json['lat'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$StoreInRadiusToJson(StoreInRadius instance) =>
    <String, dynamic>{
      'bizesId': instance.bizesId,
      'bizesNm': instance.bizesNm,
      'brchNm': instance.brchNm,
      'indsLclsCd': instance.indsLclsCd,
      'indsLclsNm': instance.indsLclsNm,
      'indsMclsCd': instance.indsMclsCd,
      'indsMclsNm': instance.indsMclsNm,
      'indsSclsCd': instance.indsSclsCd,
      'indsSclsNm': instance.indsSclsNm,
      'ksicCd': instance.ksicCd,
      'ksicNm': instance.ksicNm,
      'ctprvnCd': instance.ctprvnCd,
      'ctprvnNm': instance.ctprvnNm,
      'signguCd': instance.signguCd,
      'signguNm': instance.signguNm,
      'adongCd': instance.adongCd,
      'adongNm': instance.adongNm,
      'ldongCd': instance.ldongCd,
      'ldongNm': instance.ldongNm,
      'lnoCd': instance.lnoCd,
      'plotSctCd': instance.plotSctCd,
      'plotSctNm': instance.plotSctNm,
      'bldMngNo': instance.bldMngNo,
      'hoNo': instance.hoNo,
      'lnoAdr': instance.lnoAdr,
      'rdnmCd': instance.rdnmCd,
      'rdnm': instance.rdnm,
      'bldNm': instance.bldNm,
      'rdnmAdr': instance.rdnmAdr,
      'oldZipcd': instance.oldZipcd,
      'newZipcd': instance.newZipcd,
      'dongNo': instance.dongNo,
      'flrNo': instance.flrNo,
      'lon': instance.lon,
      'lat': instance.lat,
      'bldMnno': instance.bldMnno,
      'lnoMnno': instance.lnoMnno,
      'lnoSlno': instance.lnoSlno,
      'bldSlno': instance.bldSlno,
    };
