name: nameum_types
description: Custom class for firestore methods.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3
  json_serializable: ^6.3.1
  build_runner: ^2.2.0