name: firebase_custom
description: Custom class for firebase methods.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  nameum_types:
    path: ../nameum_types
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.4
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.3